name: Build and Deploy Documentation

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout the code
      uses: actions/checkout@v3  # Updated to v3

    - name: Set up Python
      uses: actions/setup-python@v3  # Updated to v3
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt  # Ensure sphinx and sphinx_rtd_theme are in requirements.txt

    - name: Build the documentation
      run: |
        cd docs
        make html  # Build the HTML docs with Sphinx

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}  # GitHub Actions automatically provides this
        publish_dir: ./docs/_build/html  # Path to the built HTML docs
        publish_branch: gh-pages
        keep_files: false
