name: Build and Deploy Documentation

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout the code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'  # Use your desired Python version

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install sphinx
        pip install sphinx_rtd_theme

    - name: Build the documentation
      run: |
        cd docs
        make html  # Build the HTML docs with Sphinx

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}  # GitHub Actions automatically provides this
        publish_dir: docs/build/html  # Path to the built HTML docs
        publish_branch: gh-pages  # Target branch for GitHub Pages
        keep_files: false  # Optional: Keep existing files in the branch
